version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: task-manager-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: taskdb
    volumes:
      - mongodb_data:/data/db
    networks:
      - task-manager-network

  app:
    build: .
    container_name: task-manager-app
    ports:
      - "5001:5000"
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: taskdb
      PORT: 5000
      SECRET_KEY: dev-secret-key-change-in-production-12345678901234567890
    depends_on:
      - mongodb
    networks:
      - task-manager-network

networks:
  task-manager-network:
    driver: bridge

volumes:
  mongodb_data:
